import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:provider_state_management/provider/add_to_cart_provider.dart';

class CartItemsScreen extends StatefulWidget {
  const CartItemsScreen({super.key});

  @override
  State<CartItemsScreen> createState() => _CartItemsScreenState();
}

class _CartItemsScreenState extends State<CartItemsScreen> {
  @override
  Widget build(BuildContext context) {

    var _myAddedCartItemsList = context.watch<AddToCartProvider>().myCartList;

    return Scaffold(
      appBar: AppBar(
        title: Center(child: Text("My List   (${_myAddedCartItemsList.length})",style: TextStyle(color: Colors.white),)),backgroundColor: Colors.red,
      ),

      body: ListView.builder(
        itemCount: _myAddedCartItemsList.length,
          itemBuilder: (context, index) {
          final currentMovieAddedToCart = _myAddedCartItemsList[index];  // storing the '_myAddedCartItemsList' index-wise on "currentMovieAddedToCart" object
            return Card(
              key: ValueKey(currentMovieAddedToCart.title),
              elevation: 4,
              child: ListTile(
                title: Text(currentMovieAddedToCart.title),
                subtitle: Text(currentMovieAddedToCart.duration ?? ''),
                trailing: TextButton(
                    onPressed: () {
                      // if the current item is in the cart then remove it on click of remove button

                      // 'currentMovieAddedToCart' object has the list of all movies index-wise, which are in the cart. And here the 'card' is generated by 'ListView.builder' as object and thus each card has by default a specific index.
                      //... Thus when we click { "remove" the 'currentMovieAddedToCart' } means by default the list will pick up that specific list item index-wise which is clicked and remove it from cart list

                     context.read<AddToCartProvider>().removeFromList(currentMovieAddedToCart);
                    },

                    child: const Text(
                      'Remove',
                      style: TextStyle(color: Colors.red),
                    )
                ),
              ),
            );
          },
      ),
    );
  }
}
